### ISSUE TITLE
使用tcpclient和TcpServer发现大量网络拥塞

### ISSUE THREAD

**Issue by lixinhan2019** [xia-chu/ZLToolKit#41]
在用tcpclient和TcpServer的时候发现用大量TCP Out-of-Order,TCP ACKed unseen segment,Tcp dup ack包,还是在局域网情况下测试
请问这正常吗?您对TCP的网络拥塞,乱序问题处理有什么好方法?

**Comment by xia-chu** [comment]
tcp乱序根应用程序无关



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixinhan2019 <notifications@github.com&gt;
发送时间: 2020年11月5日 19:43
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 使用tcpclient和TcpServer发现大量网络拥塞 (#41)





 
在用tcpclient和TcpServer的时候发现用大量TCP Out-of-Order,TCP ACKed unseen segment,Tcp dup ack包,还是在局域网情况下测试
 请问这正常吗?您对TCP的网络拥塞,乱序问题处理有什么好方法?

**Comment by lixinhan2019** [comment]
那没法优化吗?能给点建设性的意见?现在还是在局域网测试,以后到了公网岂不是炸了

**Comment by xia-chu** [comment]
已经在公网久经考验了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixinhan2019 <notifications@github.com&gt;
发送时间: 2020年11月5日 19:54
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 使用tcpclient和TcpServer发现大量网络拥塞 (#41)





 
那没法优化吗?能给点建设性的意见?现在还是在局域网测试,以后到了公网岂不是炸了

**Comment by lixinhan2019** [comment]
好吧... ...
