### ISSUE TITLE
接收长字符串问题

### ISSUE THREAD

**Issue by CasonTsai** [xia-chu/ZLToolKit#50]
在用测试例子tcp client和echo server传输由图片转成的base64字符串时，服务器端接收的字符串总是丢失一大段字符串
![image](https://user-images.githubusercontent.com/18262642/109471232-707a6d80-7aab-11eb-812a-d8d5a0e979fa.png)
在上面的里打印buf->data()的长度发现与client发送的不一致，小了很多

非常感谢大佬的作品，

**Comment by xia-chu** [comment]
会分成多次收到的 tcp是流 所以 你可能收到的次数跟发送的次数不一样

**Comment by CasonTsai** [comment]
@xia-chu  那请问是要在服务器端的onRecv里做多次接收处理么，要如何判断是否完成一次完整的接收

**Comment by xia-chu** [comment]
tcp都要处理粘包和分包的问题 你要在最开始就指定文件的长度 你要自己设计协议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CasonTsai <notifications@github.com&gt;
发送时间: 2021年3月1日 16:39
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 接收长字符串问题 (#50)

**Comment by CasonTsai** [comment]
好的，谢谢大佬
